[[pattern]]
id = "readme"
fixed = 'README'

[[pattern]]
id = "lic-exceptions"
fixed = 'Licensing exceptions'

[[pattern]]
id = "dual-licence"
regex = 'MIT OR Apache-2\.0|Apache-2\.0 OR MIT|dual[- ]licen'

[[pattern]]
id = "mpl"
regex = '\bMPL\b'

[[pattern]]
id = "upstream-sync"
regex = '[Uu]pstream sync'
